### 登录接口，获取token
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "username":"admin",
  "password":"123456"
}

### 提交评价接口
POST http://localhost:8080/api/evaluation/submit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkyOTE0NzAsImV4cCI6MTc4OTM3Nzg3MH0.D4a3SxTScSJcJF2bpUTHxnjNBRND8R96XXqqHuXl4G8

{
    "objectType": "community",
    "objectId": 1,
    "score": 4,
    "content": "小区配套设施不错，生活便利"
}


### 评价审核接口
POST http://localhost:8080/api/evaluation/audit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkyOTE0NzAsImV4cCI6MTc4OTM3Nzg3MH0.D4a3SxTScSJcJF2bpUTHxnjNBRND8R96XXqqHuXl4G8

{
    "id": 2,
    "status": 1,
    "rejectReason": ""
}

### 查询全部评价列表
GET http://localhost:8080/api/evaluation/list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkyOTE0NzAsImV4cCI6MTc4OTM3Nzg3MH0.D4a3SxTScSJcJF2bpUTHxnjNBRND8R96XXqqHuXl4G8

### 查询待审核评价列表 status=0
GET http://localhost:8080/api/evaluation/list?status=0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkyOTE0NzAsImV4cCI6MTc4OTM3Nzg3MH0.D4a3SxTScSJcJF2bpUTHxnjNBRND8R96XXqqHuXl4G8

### 根据ID查询评价详情
GET http://localhost:8080/api/evaluation/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkyOTcwNjEsImV4cCI6MTc4OTM4MzQ2MX0.SVw1jC7_5dVy0BMCqUL4U0O6xRv9A68cVVXI6F9OJnM

### 删除评价
DELETE http://localhost:8080/api/evaluation/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkyOTcwNjEsImV4cCI6MTc4OTM4MzQ2MX0.SVw1jC7_5dVy0BMCqUL4U0O6xRv9A68cVVXI6F9OJnM

### 查询本人提交的评价列表
GET http://localhost:8080/api/evaluation/myList
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkyOTE0NzAsImV4cCI6MTc4OTM3Nzg3MH0.D4a3SxTScSJcJF2bpUTHxnjNBRND8R96XXqqHuXl4G8

### 评价统计接口（前端图表饼图使用，返回待审核/通过/驳回数量）
GET http://localhost:8080/api/evaluation/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkyOTE0NzAsImV4cCI6MTc4OTM3Nzg3MH0.D4a3SxTScSJcJF2bpUTHxnjNBRND8R96XXqqHuXl4G8


### 添加收藏
POST http://localhost:8080/api/favorite/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkzMDEyNzcsImV4cCI6MTc4OTM4NzY3N30.2h2qP_MYERpBfVdt_cUFAqTOl_OP7ObiXb10YJQPZDY

{
"userId":1,
"objectType":"community",
"objectId":2,
"remark":"喜欢这个小区"
}



### 取消收藏
DELETE http://localhost:8080/api/favorite/delete?userId=1&objectType=community&objectId=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkzMDEyNzcsImV4cCI6MTc4OTM4NzY3N30.2h2qP_MYERpBfVdt_cUFAqTOl_OP7ObiXb10YJQPZDY

### 获取我的收藏列表
GET http://localhost:8080/api/favorite/list?userId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkzMDA0NTgsImV4cCI6MTc4OTM4Njg1OH0.xpb3knf22S7ETP1-z6PKeoPAKb7gltPD0uGUF06um2w

### 判断是否收藏
GET http://localhost:8080/api/favorite/isCollect?userId=1&objectType=community&objectId=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkzMDEyNzcsImV4cCI6MTc4OTM4NzY3N30.2h2qP_MYERpBfVdt_cUFAqTOl_OP7ObiXb10YJQPZDY

### 1. 新增分析方案 POST /api/plan
POST http://localhost:8080/api/plan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkzMDIxOTIsImV4cCI6MTc4OTM4ODU5Mn0.1P7-Y5yoDO_foXipVRykzpt-K8O11B5TOq8ON_CNIsk

{
  "userId": 1,
  "planName": "张店区15分钟生活圈方案01",
  "startType": "community",
  "startLon": 118.0256,
  "startLat": 36.8042,
  "startCommunityId": 1,
  "timeMin": 15,
  "facilityTypes": "[\"超市\",\"社区医院\"]",
  "weights": "[0.5,0.5]",
  "priceMin": 0,
  "priceMax": 200
}



### 3. 查询方案列表（按用户ID）GET /api/plan/list/{userId}
GET http://localhost:8080/api/plan/list/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkzMDQ0MzYsImV4cCI6MTc4OTM5MDgzNn0.jwJIeE2kLpO1OvKQTtuVybI6e8UFw0LvOvPgZZCcPZ8

### 4. 根据ID查询方案详情 GET /api/plan/{id}
GET http://localhost:8080/api/plan/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkzMDQ0MzYsImV4cCI6MTc4OTM5MDgzNn0.jwJIeE2kLpO1OvKQTtuVybI6e8UFw0LvOvPgZZCcPZ8


### 5. 修改方案 PUT /api/plan/{id}
PUT http://localhost:8080/api/plan/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkzMDQ0MzYsImV4cCI6MTc4OTM5MDgzNn0.jwJIeE2kLpO1OvKQTtuVybI6e8UFw0LvOvPgZZCcPZ8

{
  "planName": "修改后的方案名称",
  "timeMin":15,
  "facilityTypes":"[\"小学\",\"药店\"]"
}

### 6. 删除方案 DELETE /api/plan/{id}
DELETE http://localhost:8080/api/plan/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVDb2RlIjoiYWRtaW4iLCJpYXQiOjE3ODkzMDQ0MzYsImV4cCI6MTc4OTM5MDgzNn0.jwJIeE2kLpO1OvKQTtuVybI6e8UFw0LvOvPgZZCcPZ8

