server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: "1"
    url: jdbc:sqlserver://localhost:1433;databaseName=LifeCircleDB;encrypt=false;trustServerCertificate=true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
